spring.application.name=api_productos
# Servidor
server.port=1110
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/productos_nelson
spring.datasource.username=root
spring.datasource.password=mogadex123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#  Jackson (JSON)
spring.jackson.serialization.indent-output=true
#  Nombre de la app